// Cost view — fetches /_claudit/api/cost (and /trends?dim=model,project
// for the per-row sparkline column) and paints the four cost subviews:
// By model · By project · By skill / slash command · Top expensive
// prompts. Mirrors the SSR'd output of the legacy fat-HTML report so
// the SPA's #cost reads visually identical to /#cost.

import { fetchCost, fetchTrends } from './api.js';
import { fmtMoney, fmtPct, fmtNum, escHtml, truncate, pct } from './format.js';
import { trendSpark } from './charts.js';
import {
  buildRows, withTrend, injectTrendColumn, wireGlobalFilters,
} from './table.js';
import { hbarListSkeleton, tableBodySkeleton } from './skeleton.js';

const labelIcon = id => `<svg class="icon" aria-hidden="true"><use href="#icon-${id}"/></svg>`;

function hbarRowHTML(label, cost, totalCost, extra, truncateLabel) {
  const pctW = totalCost > 0 ? (100 * cost / totalCost).toFixed(1) : '0.0';
  const visible = truncateLabel ? truncate(label, 70) : label;
  const extraVal = extra
    ? extra
    : ` (${totalCost > 0 ? (100 * cost / totalCost).toFixed(1) + '%' : '—'})`;
  return `<div class="hbar">
    <div class="fill" style="width:${pctW}%"></div>
    <div class="lbl" title="${escHtml(label)}">${escHtml(visible)}</div>
    <div class="val">${escHtml(fmtMoney(cost))}${escHtml(extraVal)}</div>
  </div>`;
}

function modelBarsHTML(rows, totalCost) {
  const priced = rows.filter(r => r.CostUSD > 0);
  if (priced.length === 0) {
    return `<p class="small empty-state">No priced model data. Add prices for any unknown models in <code>~/.config/claudit/prices.yaml</code>.</p>`;
  }
  return priced.map(r => hbarRowHTML(r.Model, r.CostUSD, totalCost, '', false)).join('');
}

function projectBarsHTML(rows, totalCost) {
  return rows.slice(0, 20)
    .map(r => hbarRowHTML(r.Project, r.CostUSD, totalCost, '', true)).join('');
}

const SHELL = `
  <header class="view-head"><h1>${labelIcon('cost')}Cost</h1></header>
  <details class="guide">
    <summary>How to read this section</summary>
    <div class="body">
      <ul>
        <li><strong>By model</strong> — what fraction of spend went to each model. Opus dominating is expected for hard work; if it's also serving small or repetitive tasks, those are candidates to route to Sonnet or Haiku.</li>
        <li><strong>By project</strong> — which working directories cost the most. A surprise winner here is usually a side project quietly running up more spend than you realized.</li>
        <li><strong>By skill &amp; slash command</strong> — cost per invoked <code>/command</code> or skill. A high <em>cost-per-call</em> ratio flags candidates for tightening (smaller starting context, less tool output) or replacement.</li>
        <li><strong>Top expensive prompts</strong> — recurring prompts that kicked off long, costly turn chains. Repeated expensive prompts often justify a custom skill or compact agent that does the same job with less context.</li>
      </ul>
    </div>
  </details>

  <nav class="subtabs" aria-label="Cost sections">
    <a class="subtab is-active" href="#cost/model"   data-subtab="model">By model</a>
    <a class="subtab"           href="#cost/project" data-subtab="project">By project</a>
    <a class="subtab"           href="#cost/skill"   data-subtab="skill">By skill &amp; slash command</a>
    <a class="subtab"           href="#cost/prompt"  data-subtab="prompt">Top expensive prompts</a>
  </nav>

  <div class="subview is-active" data-subview="model">
    <div class="hbar-list" id="cost-bars-model"></div>
    <table data-table="model">
      <thead><tr>
        <th data-key="Model" title="Claude model ID, e.g. claude-sonnet-4-6.">Model</th>
        <th data-key="CostUSD" class="num" title="Dollar cost of all assistant turns on this model in this window. Priced via ~/.config/claudit/prices.yaml.">Cost</th>
        <th data-key="Pct" class="num" title="Share of total cost in this window.">%</th>
        <th data-key="Turns" class="num" title="Number of assistant turns generated by this model.">Turns</th>
        <th data-key="OutputTokens" class="num" title="Tokens the model generated. Output is the most expensive token type per unit.">Output tokens</th>
        <th data-key="CacheReadTokens" class="num" title="Tokens served from cache (cheapest input price, ~10% of fresh input).">Cache read tokens</th>
      </tr></thead>
      <tbody></tbody>
    </table>
  </div>

  <div class="subview" data-subview="project">
    <div class="hbar-list" id="cost-bars-project"></div>
    <table data-table="project">
      <thead><tr>
        <th data-key="Project" title="Working directory the session ran in (its CWD when Claude Code was launched).">Project</th>
        <th data-key="CostUSD" class="num" title="Dollar cost of all sessions whose CWD was this project.">Cost</th>
        <th data-key="Pct" class="num" title="Share of total cost in this window.">%</th>
        <th data-key="Sessions" class="num" title="Number of distinct session IDs that ran in this project.">Sessions</th>
        <th data-key="Turns" class="num" title="Number of assistant turns across those sessions.">Turns</th>
        <th data-key="DominantModel" title="The model that produced the most output tokens in this project.">Dominant model</th>
      </tr></thead>
      <tbody></tbody>
    </table>
  </div>

  <div class="subview" data-subview="skill">
    <table data-table="skill">
      <thead><tr>
        <th data-key="Key" title="Skill name or slash-command (e.g. /review, skill:tdd) that was invoked.">Key</th>
        <th data-key="Count" class="num" title="Number of times this skill or slash command was invoked.">Calls</th>
        <th data-key="TurnCount" class="num" title="Assistant turns that ran while this skill was active.">Turns</th>
        <th data-key="CostUSD" class="num" title="Dollar cost of those turns. Cost ÷ Calls is your cost-per-invocation lever.">Cost</th>
        <th data-key="OutputTokens" class="num" title="Tokens the model generated during this skill's turns.">Output tokens</th>
      </tr></thead>
      <tbody></tbody>
    </table>
  </div>

  <div class="subview" data-subview="prompt">
    <div class="small">User prompts ranked by the total cost of the assistant turn chain each one kicked off. Prompts cluster on the first 120 chars of normalized text — trivially-different repeats of the same ask appear in the same row. Hover a row's snippet for the full prompt.</div>
    <table data-table="prompt" class="by-prompt-table">
      <thead><tr>
        <th data-key="Sample" title="First ~120 characters of the user prompt. Rows cluster by normalized prefix, so trivially-different repeats appear in one row. Hover the cell for full text.">Snippet</th>
        <th data-key="Invocations" class="num" title="How many times this prompt cluster was sent.">Invocations</th>
        <th data-key="Sessions" class="num" title="Distinct sessions in which this prompt was sent.">Sessions</th>
        <th data-key="TurnCount" class="num" title="Assistant turns that this prompt's chain produced (one prompt can fan out into many turns).">Turns</th>
        <th data-key="CostUSD" class="num" title="Total dollar cost of the assistant turn chain this prompt kicked off.">Cost</th>
        <th data-key="Pct" class="num" title="Share of total cost in this window.">%</th>
      </tr></thead>
      <tbody></tbody>
    </table>
  </div>
`;

// paintCostSkeletons fills the empty SHELL with shimmer placeholders.
// Each spot gets overwritten when real content arrives: hbar lists via
// innerHTML, tbodies via buildRows().
function paintCostSkeletons(container) {
  const barsModel = container.querySelector('#cost-bars-model');
  if (barsModel) barsModel.innerHTML = hbarListSkeleton(5);
  const barsProject = container.querySelector('#cost-bars-project');
  if (barsProject) barsProject.innerHTML = hbarListSkeleton(8);
  const tables = {
    model: 6, project: 6, skill: 5, prompt: 6,
  };
  for (const [name, cols] of Object.entries(tables)) {
    const tb = container.querySelector(`[data-table="${name}"] tbody`);
    if (tb) tb.innerHTML = tableBodySkeleton(cols, 6);
  }
}

function activateSubview(container, sub) {
  const subs = container.querySelectorAll('.subtab[data-subtab]');
  if (!subs.length) return;
  const wanted = sub && container.querySelector(`.subtab[data-subtab="${sub}"]`)
    ? sub
    : subs[0].dataset.subtab;
  subs.forEach(t => t.classList.toggle('is-active', t.dataset.subtab === wanted));
  container.querySelectorAll('.subview').forEach(s =>
    s.classList.toggle('is-active', s.dataset.subview === wanted));
}

function updateNavMetric(id, html) {
  const el = document.getElementById(id);
  if (!el) return;
  if (html.startsWith('<')) el.innerHTML = html;
  else el.textContent = html;
}

let painted = false;
let navPainted = false;

// paintNav fetches /cost just to derive the sidebar metric (top model
// by spend). Called from app.js at startup so the metric resolves
// before the user clicks the tab; the full paint() reuses the same
// endpoint via the server's render cache.
export async function paintNav() {
  if (navPainted || painted) return;
  let cost;
  try { cost = await fetchCost(); } catch { return; }
  const byModel = cost.by_model || [];
  const topModel = byModel.filter(r => r.CostUSD > 0)[0];
  updateNavMetric('nav-metric-cost', topModel
    ? `${truncate(topModel.Model, 18)} · ${fmtMoney(topModel.CostUSD)}`
    : '—');
  navPainted = true;
}

export async function paint(route) {
  const container = document.getElementById('view-cost');
  if (!container) return;

  if (painted) {
    activateSubview(container, route.sub);
    return;
  }

  container.innerHTML = SHELL;
  paintCostSkeletons(container);

  let cost;
  try {
    cost = await fetchCost();
  } catch (err) {
    container.innerHTML = `<header class="view-head"><h1>${labelIcon('cost')}Cost</h1></header>
      <div class="warning-card" role="alert"><strong class="danger">Failed to load cost data:</strong> ${escHtml(err.message)}</div>`;
    return;
  }

  const byModel = cost.by_model || [];
  const byProject = cost.by_project || [];
  const bySkill = cost.by_skill || [];
  const byPrompt = cost.by_prompt || [];
  // total_cost_usd ships from Go (aggregate.Totals().CostUSD) — read it
  // rather than re-summing per-row costs. The per-row pct() division
  // stays client-side (which denominator applies is a per-view choice).
  const totalCost = cost.total_cost_usd || 0;

  // SSR-equivalent hbar rendering. Static report SSRs these; the SPA
  // builds them client-side from the same data.
  const barsModel = container.querySelector('#cost-bars-model');
  if (barsModel) barsModel.innerHTML = modelBarsHTML(byModel, totalCost);
  const barsProject = container.querySelector('#cost-bars-project');
  if (barsProject) barsProject.innerHTML = projectBarsHTML(byProject, totalCost);

  // Trend column injection + sparkline data. Period+trends arrive
  // alongside the data so we know whether to inject the Trend column
  // at all. Fetched in parallel so cost rendering isn't blocked when
  // --by is unset (the common case for serve mode).
  let modelTrends = null, projectTrends = null, period = '';
  try {
    const [m, p] = await Promise.all([
      fetchTrends('model').catch(() => null),
      fetchTrends('project').catch(() => null),
    ]);
    modelTrends = m;
    projectTrends = p;
    period = (m && m.period) || (p && p.period) || '';
  } catch { /* no-op — trend column stays uninjected */ }

  const modelTable = container.querySelector('[data-table="model"]');
  const projectTable = container.querySelector('[data-table="project"]');
  if (period) {
    injectTrendColumn(modelTable, 'OutputTokens', period);
    injectTrendColumn(projectTable, 'DominantModel', period);
  }

  buildRows(modelTable, byModel, r => withTrend([
    [escHtml(r.Model), false],
    [escHtml(fmtMoney(r.CostUSD)), true, r.CostUSD],
    [pct(r.CostUSD, totalCost), true],
    [fmtNum(r.Turns), true],
    [fmtNum(r.OutputTokens), true],
    [fmtNum(r.CacheReadTokens), true],
  ], 4, modelTrends && modelTrends.series ? modelTrends.series[r.Model] : null, period, trendSpark));

  buildRows(projectTable, byProject, r => withTrend([
    [`<span class="truncate path" title="${escHtml(r.Project)}">${escHtml(r.Project)}</span>`, false],
    [escHtml(fmtMoney(r.CostUSD)), true, r.CostUSD],
    [pct(r.CostUSD, totalCost), true],
    [fmtNum(r.Sessions), true],
    [fmtNum(r.Turns), true],
    [escHtml(r.DominantModel), false],
  ], 5, projectTrends && projectTrends.series ? projectTrends.series[r.Project] : null, period, trendSpark));

  buildRows(container.querySelector('[data-table="skill"]'), bySkill, r => [
    [`<code>${escHtml(r.Key)}</code>`, false],
    [fmtNum(r.Count), true],
    [fmtNum(r.TurnCount), true],
    [escHtml(fmtMoney(r.CostUSD)), true, r.CostUSD],
    [fmtNum(r.OutputTokens), true],
  ]);

  buildRows(container.querySelector('[data-table="prompt"]'), byPrompt, r => {
    const sample = r.Sample || r.Key || '';
    const head = sample.length > 80 ? sample.slice(0, 79) + '…' : sample;
    return [
      [`<span title="${escHtml(sample)}">${escHtml(head)}</span>`, false],
      [fmtNum(r.Invocations), true],
      [fmtNum(r.Sessions), true],
      [fmtNum(r.TurnCount), true],
      [escHtml(fmtMoney(r.CostUSD)), true, r.CostUSD],
      [pct(r.CostUSD, totalCost), true],
    ];
  });

  wireGlobalFilters();
  activateSubview(container, route.sub);

  // Sidebar metric — top model by cost. Mirrors the legacy navMetrics().
  const topModel = byModel.filter(r => r.CostUSD > 0)[0];
  updateNavMetric('nav-metric-cost', topModel
    ? `${truncate(topModel.Model, 18)} · ${fmtMoney(topModel.CostUSD)}`
    : '—');

  painted = true;
  navPainted = true;
}

export function reset() { painted = false; navPainted = false; }
